### PR TITLE
Add CommonJs & AMD compatability

### PR DESCRIPTION
**Pull request by jjoos**
based on this blog post:
http://blog.npmjs.org/post/112712169830/making-your-jquery-plugin-work-better-with-npm

### CODE REVIEW

**Comment by amasad** [comment]
Cool. Can you run jshint and make sure it follows the same style? For example use 2 spaces please

**Comment by jjoos** [comment]
How do I run jshint on the project, this is the output I'm getting on my branch (jshint: v2.8.0):

```
> jshint -c .jshintrc textarea-helper.js
textarea-helper.js: line 2, col 5, Missing "use strict" statement.
textarea-helper.js: line 2, col 41, 'define' is not defined.
textarea-helper.js: line 4, col 9, 'define' is not defined.
textarea-helper.js: line 5, col 46, 'module' is not defined.
textarea-helper.js: line 7, col 9, 'module' is not defined.
textarea-helper.js: line 7, col 34, 'require' is not defined.

6 errors
```

**Comment by jjoos** [comment]
Ah I though jshint would also give feedback on style, but it doesn't. Fixed the jshint issues, changed the indentation, not completely sure I completely match your style, could you double check?

**Comment by amasad** [comment]
looks good, thanks!

**Pull request merged**
